<a href="https://colab.research.google.com/github/Bhilarevijay/python/blob/main/Assignment_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import tensorflow as tf

# 1D tensor from 1 to 10
tensor_1d = np.arange(1, 11)
# Reshape to 5 rows, 2 columns
tensor_2d = tensor_1d.reshape((5, 2))
print("1D to 2D:\n", tensor_2d)


1D to 2D:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [16]:
tensor_3d = np.random.randint(0, 10, size=(2, 3, 4))
print("3D Tensor:\n", tensor_3d)


3D Tensor:
 [[[8 6 8 7]
  [5 2 3 1]
  [3 9 7 8]]

 [[3 4 9 4]
  [1 9 0 6]
  [4 5 9 7]]]


In [17]:
tf_tensor = tf.ones((3, 3))
added_tensor = tf_tensor + 5
multiplied_tensor = added_tensor * 3
print("Tensor after adding 5 and multiplying by 3:\n", multiplied_tensor)


Tensor after adding 5 and multiplying by 3:
 tf.Tensor(
[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]], shape=(3, 3), dtype=float32)


In [18]:
def tf_dot_product(tensor_a, tensor_b):
    return tf.matmul(tensor_a, tensor_b)

# Sample input
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
result = tf_dot_product(a, b)
print("Dot product:\n", result.numpy())


Dot product:
 [[19 22]
 [43 50]]


In [19]:
A = np.random.randint(1, 10, size=(3, 2))
B = np.random.randint(1, 10, size=(2, 3))
product = np.matmul(A, B)
print("Matrix multiplication result:\n", product)


Matrix multiplication result:
 [[ 49 104  27]
 [ 21  72  23]
 [ 28  80  24]]


In [20]:
def slice_tensor(tensor):
    return tensor[:2, :, -1]

# Using the tensor_3d from earlier
sliced = slice_tensor(tensor_3d)
print("Sliced 3D tensor (first 2 rows, all cols, last depth slice):\n", sliced)


Sliced 3D tensor (first 2 rows, all cols, last depth slice):
 [[7 1 8]
 [4 6 7]]


In [21]:
zeros = tf.zeros((4, 4))
ones = tf.ones((4, 4))
concat_tensor = tf.concat([zeros, ones], axis=0)
print("Concatenated tensor along rows:\n", concat_tensor)


Concatenated tensor along rows:
 tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(8, 4), dtype=float32)


In [22]:
tensor = tf.Variable(tf.zeros((5, 5)))
tensor[1:4, 1:4].assign(tf.ones((3, 3)))
print("Updated tensor with 1s in the middle:\n", tensor.numpy())


Updated tensor with 1s in the middle:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
tensor_np = np.random.randint(5, 15, size=(4, 4))
tensor_np -= 3
reshaped_np = tensor_np.reshape((2, 8))
print("Subtracted 3 and reshaped:\n", reshaped_np)


Subtracted 3 and reshaped:
 [[ 9 10 10  4 10 11  6 11]
 [10  3  2  5  2  2  7  6]]


In [24]:
rand_tensor = tf.random.uniform((2, 2), minval=0, maxval=10, dtype=tf.int32)
result_tensor = rand_tensor - 3
print("Random tensor - 3:\n", result_tensor.numpy())


Random tensor - 3:
 [[ 6 -2]
 [ 4  4]]
