<a href="https://colab.research.google.com/github/Bhilarevijay/python/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Template of class**

class <name of the class>:
----------}attributes

----------}behavior

create obj of the class
obj.<-->

In [ ]:
class sample:
  def greet(self):
    print("Hello World")                    ##  METHOD 1 Call using object##

obj=sample()
obj.greet()

Hello World


In [ ]:
class sample:
  def greet(self):
    print("Hello World")                    ##  METHOD 2 Call using class##

obj=sample()
sample.greet(obj)

Hello World


**Special Method**

In [ ]:
class sample:

  def __init__(self) :
    print("hi i am init")

  def greet(self) :
    print("Hello World")

obj=sample()
sample.greet(obj)

hi i am init
Hello World


In [ ]:
class sample:

  def __init__(self,name,age) :
    self.name=name
    self.age=age

  def display (self):
    print(self.name)
    print(self.age)

obj1=sample("abc",18)
obj2=sample("xyz",19)
obj1.display()
obj1.name="harry"
obj1.display()
obj2.display

abc
18
harry
18


In [ ]:
class sample:
  z=10

  def __init__(self,name,age) :
    self.name=name
    self.age=age

  def display (self):
    print(self.name,self.age)

  def show(ds):
    print(ds.z)

obj=sample("xyz",17)
obj.display()
# sample.show()

xyz 17


**CLASS METHOD (DECORATORS)**

In [ ]:
class sample:
  z=10

  def __init__(self,name,age) :
    self.name=name
    self.age=age

  def display (self):
    print(self.name,self.age)

  @classmethod
  def show(cls):
    print(cls.z)

  @staticmethod
  def config():
    print("iam in config method")

obj=sample("xyz",17)
obj.display()
sample.show()
sample.config()

xyz 17
10
iam in config method


**CLASS WITHIN A CLASS**

In [ ]:
class Sample:

  def __init__(self,m1,m2) :
    self.m1=m1
    self.m2=m2

  def display (self):
    print(self.m1,self.m2)

  class Book:

    def __init__(self,name,cost):
      self.name=name
      self.cost=cost

    def show(self):
      print(self.name,self.cost)

obj1=Sample("xz",17)
obj1.display()

obj2=Sample.Book("ab",100)
obj2.show()

xz 17
ab 100


**Creating obj in obj for the class in class**

In [ ]:
class Sample:

  def __init__(self,m1,m2) :
    self.m1=m1
    self.m2=m2
    self.obj2=self.Book("python",200)     #obj for Book class in Sample class

  def display (self):
    print(self.m1,self.m2)

  class Book:

    def __init__(self,name,cost):
      self.name=name
      self.cost=cost

    def show(self):
      print(self.name,self.cost)

obj1=Sample("xz",17)
obj1.display()

obj1.obj2.show() #1
print(obj1.m1)

b=obj1.obj2      #2
b.show()

xz 17
python 200
xz
python 200


**INHERITANCE**

**1. Single level**
**2. Multi-level**
**3. Multiple**

In [ ]:
#MULTI-LEVEL
class A:
  def feature1(self):
    print("A feaure1")

class B(A):
  def feature2(self):
    print("B feature2")

class C(B):
  def feature3(self):
    print("C feature3")

obj=C()
obj.feature1()
obj.feature2()
obj.feature3()

A feaure1
B feature2
C feature3


In [ ]:
#MULTIPLE
class A:

  def __init__(self,f1,f2):
    self.f1=f1
    self.f2=f2

  def feature1(self):
    print(self.f1,self.f2)

class B:
  def __init__(self,f1,f2):
    self.f1=f1
    self.f2=f2

  def feature1(self):
    print(self.f1,self.f2)

class C(A,B):
  def feature3(self):
    print("C feature3")

obj=C()
obj.feature1()
obj.feature2()
obj.feature3()


TypeError: A.__init__() missing 2 required positional arguments: 'f1' and 'f2'

**DUCK Typing**

In [ ]:
class C:
  def feature1(self):
    print("class feature1")

class A:
  def feature1(self):
    print("class feature1")

class B:
  def feature3(self,other):
    other.feature1()

objC=C()
objA=A()
objB=B()
objB.feature3(objA)

class feature1


**OPERATOR Overloading**

In [ ]:
a=10
b=20
print(a+b)
print(int.__add__(a,b))

a="Hello"
b=10



30
30


In [ ]:
class Sample:
  def __init__(self,a,b):
    self.a=a
    self.b=b

  def __add__(self,other):   #(obj1,obj2)
    a= self.a + other.a
    b= self.b + other.b
    obj=Sample(a,b)
    return(obj)

obj1=Sample(10,20)
obj2=Sample(30,40)
obj3=obj1+obj2
print(obj3.a,obj3.b)

40 60


In [ ]:
class Sample:
  def __init__(self,a,b):
    self.a=a
    self.b=b

  def __gt__(self,other):   #(obj1,obj2)
    r1= self.a + self.b
    r2= other.a + other.b
    if r1>r2:
      return True
    else:
      return False

obj1=Sample(30,40)
obj2=Sample(10,20)
if obj1 > obj2:
  print("obj1 is greater")
else:
  print("obj2 is greater")

obj1 is greater


**METHOD Overloading**

In [ ]:
class Sample:
  def __init__(self,M1,M2):
    self.M1=M1
    self.M2=M2

  def feature1(self,a=None,b=None,c=None):
    sum=0
    if a!=None and b!=None and c!=None:
      sum=a+b+c
    elif a!=None and b!=None:
      sum=a+b
    else:
      sum=a
    return(sum)

obj=Sample(10,20)
print(obj.feature1(5,10))
print(obj.feature1(5,10,15))

15
30


**LAMBDA FUNCTION**

In [1]:
## Error

nums = [3,2,6,8,4,6,2,9]
f = lambda n : n%2==0
f(nums)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [ ]:
## Correct

from functools import reduce

nums = [3,2,6,8,4,6,2,9]

evens = list(filter(lambda n : n%2==0 , nums))
print (evens)


doubles = list(map(lambda n : n+2 , evens))
print (doubles)

[2, 6, 8, 4, 6, 2]
[4, 8, 10, 6, 8, 4]


**ROUND **

In [ ]:
circle_area=[3.55345,5.4654,4.465455,56.465465,9.6543454,32.65353554]
result = list(map(round,circle_area,range(1,7))) #round is a function
print(result)

[3.6, 5.47, 4.465, 56.4655, 9.65435, 32.653536]


In [ ]:
my_pets = ['alfred','tabitha','william','arla']
uppered_pets = []

for pet in my_pets:
  pet = pet.upper()
  uppered_pets.append(pet)

print (uppered_pets)

['ALFRED', 'TABITHA', 'WILLIAM', 'ARLA']


**ZIP**

In [ ]:
my_strings = ['a','b','c','d','e']
my_numbers = [1,2,3,4,5]

result1 = list(zip(my_strings,my_numbers))
print(result1)


result2 = list(map(lambda x,y : (x,y) , my_strings,my_numbers))
print(result2)


[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]
[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]


In [ ]:
scores = [66,54,45,77,88,99]

def is_a_student(score):
  return score > 75

over_75 = list(filter(is_a_student,scores))

print(over_75)

[77, 88, 99]


**REDUCE**

In [ ]:
from functools import reduce
num = [3,4,6,9,34,12]

def custom_sum (first,second):
  return first + second

result = reduce(custom_sum,num)  #takes two num at a time from num list
print(result)

68


In [ ]:
from functools import reduce
num = [3,4,6,9,34,12]

def custom_sum (first,second):
  return first + second

result = reduce(custom_sum,num,10)  #takes two num at a time from num list
print(result)

78


type of errors :
1. zerodivisionerror
2. nameerror (undifined)
3. typeerror (string + int )

**HANDLE EXCEPTION**

In [ ]:
try:
  result = 10/0
except ZeroDivisionError:
  print ("Error : Cannot divide by zero.")

Error : Cannot divide by zero.


In [ ]:
try:
  result = int("text")
except (ValueError,TypeError) as e:
  print ("Error :",e)

Error : invalid literal for int() with base 10: 'text'


cProfiler(Built-in Profiler)

It is built in python profiler that analyze the execution time of different pars of your code.

In [ ]:
import cProfile

def slow_fun():
  total = 0
  for i in range(1000000):
    total += i
    return total

cProfile.run('slow_fun()')

         4 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <ipython-input-21-4a2bc3bc3774>:3(slow_fun)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [ ]:
pip install line-profiler

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.2/750.2 kB 11.8 MB/s eta 0:00:00


In [ ]:
from line_profiler import LineProfiler

def slow_fun():
  total = 0
  for i in range(1000000):
    total += i

  return total

profiler =LineProfiler()
profiler.add_function(slow_fun)
profiler.enable()
slow_fun()
profiler.disable()
profiler.print_stats()


Timer unit: 1e-09 s

Total time: 0.819289 s
File: <ipython-input-11-caaec7355fb3>
Function: slow_fun at line 3

Line #      Hits         Time  Per Hit   % Time  Line Contents
     3                                           def slow_fun():
     4         1       1637.0   1637.0      0.0    total = 0
     5   1000001  367250176.0    367.2     44.8    for i in range(1000000):
     6   1000000  452036706.0    452.0     55.2      total += i
     7                                               
     8         1        921.0    921.0      0.0    return total



In [ ]:
def count_up_to(n):
      i = 1
      while i <= n:
        yield i
        i += 1

for num in count_up_to(5):
  print(num)

SyntaxError: invalid syntax (<ipython-input-17-8f39132dcb86>, line 1)

In [ ]:
pip install numpy

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
zeros = np.zeros((2, 3))  # 2x3 matrix of zeros
ones = np.ones((3, 3))    # 3x3 matrix of ones
rand = np.random.rand(3, 3)  # 3x3 matrix with random values

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (2, 3) -> Rows x Columns
print(arr.size)   # 6 -> Total number of elements
print(arr.ndim)   # 2 -> Number of dimensions
print(arr.dtype)  # int64 -> Data type
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])    # 10 (First element)
print(arr[-1])   # 50 (Last element)

(2, 3)
6
2
int64
10
50


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[1, 2])  # 6 (Row 1, Column 2)

6


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])   # [20 30 40]
print(arr[:3])    # [10 20 30]
print(arr[-3:])   # [30 40 50]

[20 30 40]
[10 20 30]
[30 40 50]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a ** 2) # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


In [ ]:
arr = np.array([10, 20, 30, 40])

print(arr.sum())  # 100
print(arr.mean()) # 25.0
print(arr.max())  # 40
print(arr.min())  # 10
print(arr.std())  # Standard deviation

100
25.0
40
10
11.180339887498949


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))  # 2 rows, 3 columns
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.T)  # Transpose (flips rows and columns)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))  # Horizontal stack
print(np.vstack((a, b)))  # Vertical stack

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 2))  # Split into 2 parts

[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])  # [30 40 50]

[30 40 50]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr % 2 == 0, "Even", "Odd"))  # ['Odd' 'Even' 'Odd' 'Even' 'Odd']

['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))  # Matrix multiplication

[[19 22]
 [43 50]]


In [ ]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.det(matrix))

-2.0000000000000004


In [ ]:
matrix = np.array([[2, 3], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[-0.16227766  6.16227766]
[[-0.81124219 -0.58471028]
 [ 0.58471028 -0.81124219]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

np.save('array.npy', arr)  # Save
loaded_arr = np.load('array.npy')  # Load
print(loaded_arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
import time

size = 10**6

# Python List
python_list = list(range(size))
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print(f"Python List Time: {end - start:.5f} sec")

# NumPy Array
numpy_array = np.arange(size)
start = time.time()
numpy_result = numpy_array * 2
end = time.time()
print(f"NumPy Array Time: {end - start:.5f} sec")

Python List Time: 0.21576 sec
NumPy Array Time: 0.00866 sec
